### ISSUE TITLE
What's in that firmware?

### ISSUE THREAD

**Issue by TheNitek** [fritzchentastig/NX300M-MFW#1]
Can you provide a little bit more details which i firmware this version is based on and what has been changed?

**Comment by fritzchentastig** [comment]
Yes
This is the 1.15 Firmware, but with libmisc.so from the 1.10. And busybox from the 1.10 and the telnetd,ftpd and chroot symlinks to the busybox were replaced with the 1.10 busybox because 1 Samsung deleted those symlinks and 2 creation of new symlinks is not possible so I had to use the binary. 
That's about it.

**Comment by fritzchentastig** [comment]
added it to the readme 
closing this issue
